config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index' 
  # Sessions
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # Message
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15 }, uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  
  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", message_node: message_render(message)
    end
  end

  private 

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "Wrong username or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect  
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.slim
h4.ui.center.aligned.medium.icon.header
  i.circular.coffee.icon.orange
  | Say something
.ui.two.column.grid
  /! LEFT COLUMN
  .twelve.wide.column
    /! CHAT CARD
    .ui.card.fluid.chatbox
      header.content
        h4.ui.header Chatroom
      .content.chatroom__messages-wrapper
        .ui.feed#chatroom-messages
          = render @messages
      .extra.content
        = form_for(@message, html: { class: 'ui reply form', role: 'form' }, url: message_path, remote: true) do |f|
          .field
            .ui.fluid.icon.input
              = f.text_field :body, placeholder: 'Enter message...', autofocus: true, id: 'chatroom-submit'
              = f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe
  /! RIGHT COLUMN
  .four.wide.column
    /! CHAT MENU
    .ui.vertical.inverted.menu
      a.active.item
        | Inbox
        .ui.teal.left.pointing.label 1
      a.item
        | Spam
        .ui.label 51
      a.item
        | Updates
        .ui.label 1
      .item
        .ui.transparent.icon.input
          input placeholder=("Search mail...") type="text" /
          i.search.icon

app/views/layouts/_alerts.html.slim
- flash.each do |message_type, message_content| 
  .ui.message.transition class=message_type
    i.close.icon
    .header
      = message_content

app/views/layouts/_navigation.html.slim
= link_to 'Chatroom', root_path, class: 'active item'
a.item Messages
.right.menu
  .ui.dropdown.item
    | Account
    i.dropdown.icon
    .menu
      - if logged_in?
        = link_to 'Log Out', logout_path, method: :delete, class: 'item'
      - else
        = link_to 'Log In', login_path, class: 'item'
  .item
    - if !logged_in?
      = link_to 'Sign Up', login_path, class: 'ui orange button'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RealTimeMessageApp</title>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="ui inverted menu">
    <div class="ui container">
      <%= render 'layouts/navigation' %>
    </div>
  </div>
  <div class="ui container">
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </div>
</body>

</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %>:</em> <%= message.body %>
    </div>
  </div>
</div>